### ISSUE TITLE
Error when send message

### ISSUE THREAD

**Issue by Kwak04** [Kwak04/Lets-Chat#53]
### 메시지를 첫 번째 보낼 때는 잘 가는데 항상 두 번째 시도에서 오류를 뿜으며 앱이 정지됨.

**Comment by Kwak04** [comment]
#### error code:
`emulator-5554]: E/EventThread: Task threw exception
    java.lang.NullPointerException: rhs == null
        at java.lang.String.compareTo(Native Method)
        at com.example.soenapp.ChatActivity$3$1.compare(ChatActivity.java:153)
        at com.example.soenapp.ChatActivity$3$1.compare(ChatActivity.java:150)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.util.TimSort.sort(TimSort.java:220)
        at java.util.Arrays.sort(Arrays.java:1492)
        at java.util.ArrayList.sort(ArrayList.java:1470)
        at java.util.Collections.sort(Collections.java:206)
        at com.example.soenapp.ChatActivity$3.call(ChatActivity.java:150)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.client.Socket.onevent(Socket.java:338)
        at io.socket.client.Socket.onpacket(Socket.java:289)
        at io.socket.client.Socket.access$100(Socket.java:24)
        at io.socket.client.Socket$2$2.call(Socket.java:120)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.client.Manager.ondecoded(Manager.java:427)
        ...`

**Comment by RioChoi** [comment]
> ### 메시지를 첫 번째 보낼 때는 잘 가는데 항상 두 번째 시도에서 오류를 뿜으며 앱이 정지됨.

.....파이팅

**Comment by Kwak04** [comment]
> > ### 메시지를 첫 번째 보낼 때는 잘 가는데 항상 두 번째 시도에서 오류를 뿜으며 앱이 정지됨.
> 
> .....파이팅

감사합니다....

**Comment by Kwak04** [comment]
server: Kwak04/LetsChat-server#10
